#api for creating an admin user 

###
POST http://127.0.0.1:8000/turfs/admin-register/
Content-Type: application/json

{
    "username":"admin123",
    "email":"admin123@gmail.com",
    "password":"admin@123"
}

#api call for listing all turf details

###
GET http://127.0.0.1:8000/turfs/
Accept: application/json
Authorization: Basic admin123:admin@123

#api call for creating turf details 
###
POST http://127.0.0.1:8000/turfs/
Content-Type: application/json
Authorization: Basic admin123:admin@123

{
        "name": "royal blasters ",
        "location": "Edappally, Kochi",
        "phone": "8084593569",
        "fee": 184
    }


#api call for fetching a record

###
GET http://127.0.0.1:8000/turfs/3/
Accept: application/json
Authorization: Basic admin123:admin@123

#api call for updating a record 
###
PUT  http://127.0.0.1:8000/turfs/7/
Content-Type: application/json
Authorization: Basic admin123:admin@123

  {
    "id": "7",
    "name": "royal blasters",
    "location": "Edappally, Kochi",
    "phone": "8084593569",
    "fee": 1560
  }

# api call for deleting a record 

###
DELETE  http://127.0.0.1:8000/turfs/3/
Accept: application/json
Authorization: Basic admin123:admin@123

#BOOKINGS ENDPOINTS

#api call for listing all bookings/Reservations

###
GET http://127.0.0.1:8000/bookings/
Accept: application/json



#============== v2 endpoints =========

#api call for creating a new user

###
POST http://127.0.0.1:8000/v2/bookings/signup/
Content-Type: application/json

{
  "username":"alysha123",
  "email":"ayshanasrin23@gmail.com",
  "password":"aayshaa@123"
}


# api call for listing all turf reservations

###
GET http://127.0.0.1:8000/v2/bookings/reservations/
Accept: application/json


# api call for creating Turf Reservations

###
POST http://127.0.0.1:8000/v2/bookings/reservations/
Content-Type: application/json

{
    "team_name": "blaster56 ",
    "turf": 1,
    "phone_number": "9876543217",
    "email": "blaster56@gmail.com",
    "date": "2026-10-7",
    "start_time": "11:00:00",
    "match_duration": "02:00:00"
}
