# Generated by Django 5.2.17 on 2026-10-05 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turf_reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='created_at',
        ),
    ]
